Select * from "VADIVEL"."STD" WHERE ID DEACTIVATED='TRUE'
LOCK TABLE "VADIVEL"."STD" IN WRITE MODE WAIT

Select * from "VADIVEL"."STD" WHERE NAME='TRUE';   STD--"VADIVEL"."STD"

Select * from STD -- WHERE NAME='FALSE';

Select * from STD "VADIVEL"."STD" 

LOCK TABLE "VADIVEL"."STD" IN EXCLUSIVE MODE;

 SELECT * FROM "VADIVEL"."STD" FOR UPDATE;
 
   ENQUEUE_ "VADIVEL"."STD";
   
  SELECT * FROM "VADIVEL"."STD"
WHERE NAME > 'OOO';
commit;


